import { MenusList } from '@/common/interfaces/menus-list';

export const MenusListData: MenusList = [
  {
    name: '主页',
    icon: 'icon-home',
    activeIcon: '',
    hidden: false,
    key: 'home',
    routeUrl: 'dashboard/workplace',
    routeName: 'dashboard',
    redirect: '',
    meta: {
      title: '主页',
    },
    children: [
      {
        name: '工作台',
        key: 'workplace',
        icon: 'IconDashboard',
        activeIcon: '',
        hidden: false,
        routeUrl: '',
        routeName: 'workplace',
        redirect: '',
        componentPath: 'dashboard/workplace/index.tsx',
        meta: {
          title: '工作台',
        },
        children: [],
      },
    ],
  },
  {
    name: '资产',
    icon: 'icon-me',
    key: 'asset',
    activeIcon: '',
    hidden: false,
    routeUrl: '',
    routeName: '',
    redirect: '',
    meta: {
      title: '资产管理',
    },
    children: [
      {
        name: '用户管理',
        icon: 'icon-me',
        key: 'userManage',
        activeIcon: '',
        hidden: false,
        routeUrl: '',
        routeName: '',
        redirect: '',
        meta: {
          title: '用户管理',
        },
        children: [
          {
            name: '用户管理',
            key: 'normalUserManage',
            icon: '',
            activeIcon: '',
            hidden: false,
            routeName: 'normalUserManage',
            routeUrl: '',
            redirect: '',
            componentPath: 'user-manage/user-manage/UserManage.tsx',
            meta: {
              title: '用户管理',
            },
            children: [],
          },
          {
            name: '管理员管理',
            key: 'adminUserManage',
            icon: '',
            activeIcon: '',
            hidden: false,
            routeUrl: '',
            routeName: 'adminUserManage',
            redirect: '',
            componentPath: 'user-manage/admin-user-manage/AdminUserManage.tsx',
            meta: {
              title: '管理员管理',
            },
            children: [],
          },
          {
            name: '角色管理',
            key: 'roleManage',
            icon: '',
            activeIcon: '',
            hidden: false,
            routeUrl: '',
            routeName: 'roleManage',
            redirect: '',
            componentPath: 'user-manage/role-manage/RoleManage.tsx',
            meta: {
              title: '角色管理',
            },
            children: [],
          },
        ],
      },
    ],
  },
  // {
  //   name: '设置',
  //   icon: 'icon-setting',
  //   key: 'setting',
  //   activeIcon: '',
  //   hidden: false,
  //   routeUrl: 'setting',
  //   routeName: '',
  //   redirect: '',
  //   meta: {
  //     title: '设置',
  //   },
  //   children: [
  //     {
  //       name: '导航管理',
  //       key: 'routeManage',
  //       icon: 'IconTool',
  //       activeIcon: '',
  //       hidden: false,
  //       routeUrl: 'routeManage',
  //       routeName: '',
  //       redirect: '',
  //       meta: {
  //         title: '导航管理',
  //       },
  //       children: [
  //         {
  //           name: '导航列表',
  //           key: 'routeList',
  //           icon: 'IconMindMapping',
  //           activeIcon: '',
  //           hidden: false,
  //           routeUrl: 'routeList',
  //           routeName: '',
  //           redirect: '',
  //           componentPath: 'route-manage/route-list/RouteList.tsx',
  //           meta: {
  //             title: '导航列表',
  //           },
  //           children: [],
  //         },
  //       ],
  //     },
  //   ],
  // },
];
